def print_ambro():
    print("                                                         :AmbRo:")
    print("                                                AB@@B@b@b@BBA.")
    print("                                        AG@B@BMMMMB@@B2B2A")
    print("                                   :A@B@b@MMMMMMMB@B@B@A")
    print("                            :A@B@B@MMMMMMMMMMMMM@B@B@A")
    print("                    :A@B@B@MMMMMMMMMMMMMMMMMM@B@BA")
    print("            :A@B@B@MMMMMMMMMMMMMMMMMMMMM@B@B@A")
    print("            :A@B@                MMMMMMMMMMMMM             @B@B@@@A")
    print("            :A@B@                     MMMMMMMMMM                     @B@@@A")
    print("            :A@B@                      MMMMMMMMM                          B@@@A")
    print("            :A@B@                      MMMMMMMMM                          @@@A")
    print("            :A@B@                     MMMMMMMMM                           @@@A")
    print("            :A@B@                   MMMMMMMMMM                        @@@A")
    print("            :A@B@B              MMMMMMMMMMMM                    @B@@@A")
    print("            :A@B@B@  MMMMMMMMMMMMMMMMMMMM  B@B@@@A")
    print("            :A@B@B@  MMMMMMMMMMMMMMMMMMMM  B@B@@@A")
    print("            :A@B@B@  MMMMMMMMMMMMMMMMMMMM  B@B@@@A")
    print("            :A@B@B@  MMMMMMMMMMMMMMMMMMMM  B@B@@@A")
    print("                     :A@B@B@OOOOOOOOOOOOOOOOOOOOO@B@B@A")
    print("                          :A@B@B@OOOOOOOOOOOOOOOO@B@B@A")
    print("                                  :A@B@bOOOOOOOOOOOOO@B@BA")
    print("                                      AG@B@OOOOOOOOOOOB2B2A")
    print("                                              AB@OOOOOOOO@BA")
    print("                                                         :aMBrO:")

# Calling the function to print the ASCII art
print_ambro()
